name: sui
description: A cross-platform SDK for Sui blockchain, supporting Mobile, Web and Desktop.
version: 0.4.0
homepage: https://github.com/mofalabs/sui

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  bs58check: ^1.0.2
  ed25519_edwards: ^0.3.1
  pointycastle: ^4.0.0
  bcs: ^0.1.2
  dio: ^5.10.0
  hex: ^0.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  web_socket_channel: ^3.0.3
  protobuf: ^4.1.0
  fixnum: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

